version: 2

project_name: applink

before:
  hooks:
    - go mod tidy

builds:
  - id: applink
    main: ./cmd/applink
    binary: applink
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: jaknapp
    name: applink
  draft: false
  prerelease: auto

brews:
  - name: applink
    repository:
      owner: jaknapp
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/jaknapp/applink"
    description: "CLI tool for authenticating with OAuth services and managing MCP configurations"
    license: "MIT"
    install: |
      bin.install "applink"
    test: |
      system "#{bin}/applink", "--version"
